version: '3.7'
services:

  eureka-service:
    image: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8761:8761"
    networks:
      - xml-network
    container_name: eureka-service
    restart: on-failure
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/


  zuul-api-gateway-service:
    image: zuul-api-gateway-service
    build:
      context: ./zuul-api-gateway-service
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8091:8091"
    networks:
      - xml-network
    depends_on:
      - eureka-service
    container_name: zuul-api-gateway-service
    restart: on-failure
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - xml-network
    ports:
    - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: igor
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: igor
      MYSQL_DATABASE: xml

  authentication-service:
    image: authentication-service
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8083:8083"
    networks:
        - xml-network
    container_name: authentication-service
    restart: on-failure
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: igor
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: xml
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    depends_on:
      - mysql
      - eureka-service

networks:
  xml-network:
    name: xml-network
    driver: bridge
