//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.01 at 06:41:33 PM CEST 
//


package com.xml.soap.code;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8084.codebook_service_schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8084.codebook_service_schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PricelistRequest }
     * 
     */
    public PricelistRequest createPricelistRequest() {
        return new PricelistRequest();
    }

    /**
     * Create an instance of {@link PricelistResponse }
     *
     */
    public PricelistResponse createPricelistResponse() {
        return new PricelistResponse();
    }

    /**
     * Create an instance of {@link Pricelist }
     * 
     */
    public Pricelist createPricelist() {
        return new Pricelist();
    }

}
