//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.01 at 06:41:33 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8084/codebook-service-schema")
package com.xml.soap.code;
